apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app: curl
spec:
  containers:
  - image: curlimages/curl:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: curl
  restartPolicy: Always