apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsutils-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      containers:
        - name: dnsutils
          image: registry.rbsoftech.online/rbsoft/dnsutils:1.3
          command:
            - "sleep"
            - "604800"
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred-uat
