apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  containers:
  - image: mysql:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: mysql-client
  restartPolicy: Always
