apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  labels:
    app: postgres-client
spec:
  containers:
  - image: postgres:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: postgres-client
  restartPolicy: Always
